name: Webpage to PDF
on: [push]
jobs:
  export-pdf:
    runs-on: ubuntu-latest
    steps:
      - name: web to pdf
        uses: misaelnieto/web_to_pdf_action@v0.3.1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          webPageURL: https://christianbelloni.github.io/CV/
          outputFile: ./resume.pdf
      - name: release artifacts
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ./resume.pdf
