name: Webpage to PDF
on: [push]
jobs:
  export-pdf:
    runs-on: ubuntu-latest
    steps:
      - name: web to pdf
        uses: misaelnieto/web_to_pdf_action@v0.3.1
        with:
          webPageURL: https://christianbelloni.github.io/CV/
          outputFile: ./resume.pdf
